sudo: false
language: java
jdk:
- oraclejdk8
jobs:
  include:
    - stage: unit test
      script: pwd
    - script: cd initial
    - script: ./gradlew build & java -jar target/gs-spring-boot-0.1.0.jar
    - stage: auto test
      script: pwd
    - script: ../test/run.sh
