sudo: false
language: java
jdk:
- oraclejdk8
service:
- docker
jobs:
  include:
    - stage: unit test
      script:
        - cd initial
        - ./gradlew build
        - cd ..
        - cp initial/build/libs/*.jar test/gs-spring-boot.jar
        - cd test
        - docker build -t spring .
        - docker run -d -p 127.0.0.1:8090:8080 spring
        - docker ps
        - sleep 20
        - ./run.sh '127.0.0.1' '8090'
