sudo: false
language: java
jdk:
- oraclejdk8
jobs:
  include:
    - stage: unit test
      script:
        - cd initial
        - ./gradlew build
        - java -jar build/libs/gs-spring-boot-0.1.0.jar & sleep 10
    - stage: auto test
      script: test/run.sh
